name: Publish prod release
on:
  release:
    types: [published]

jobs:
  release-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: release-to-prod
        with:
          script: |
            github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'prod',
              head: context.sha,
            });

